### ISSUE TITLE
Credentials for IBM Cloud

### ISSUE THREAD

**Issue by gitjps** [hammoaj/node-red-contrib-cloudantplus#10]
I installed Node-RED v2.2.2 on macOS and the cloudantplus nodes.
Observations: 

- Node Cloudantplus does not appear in the palette 

- When I configure the properties I'm prompted for user and password. On IBM Cloud I only have username, apikey etc.

I saw this [tutorial](https://medium.com/@ml4den/connecting-to-a-cloudant-database-in-node-red-37239bfc9ede#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkZDZjYTJhODFkYzJmZWE4YzM2NDI0MzFlN2UyOTZkMmQ3NWI0NDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NDU4MjQxODEsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMTUzMTMzNzAzMjQ1MzQxMDYzNiIsImVtYWlsIjoicGV0ZXIuc2NobGVpbml0ejk5QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJuYW1lIjoiUGV0ZXIgU2NobGVpbml0eiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQU9oMTRHaTJhYVpDSXBBdlNCMWt1TDd5bEczbWZRQXhoN3VlTWVUc0R3X0FIQT1zOTYtYyIsImdpdmVuX25hbWUiOiJQZXRlciIsImZhbWlseV9uYW1lIjoiU2NobGVpbml0eiIsImlhdCI6MTY0NTgyNDQ4MSwiZXhwIjoxNjQ1ODI4MDgxLCJqdGkiOiJmYmRiZWJmNjcwNDM4NDRhNTA0NmNhY2NiYTRlYTg5ZGJiNmQ1YzI4In0.rdxjfkVRFiHh7oLd8XAdT9mOa10WQZyBy1ODV7yhQhGHBPVxJplASYKCh9Do2yK0J9h0We77VkCME0oHYZJKBAePkgewdoTvhR6ZiKfuJHUs1v-kr6W7AtCuNtnc0kpv26RNK722DE13osSfaG4Q83G3LQiO-OzI9V4bD_y_BGaGMg5lQSBtZyAHDvKzxGor9Vr4BUErHzrol4R8PXZAFGYlEE5Y79q5fkU_x2ltSz07Kww3j2tFP_VTSNhwOiLO0nEcYJq4pNjg_kShoLK-wwYT2BCfP_5xBBFgd6ZeVvZHXHUiBWlih04aVr-2StuAuDQlNJcwRVWmqsvVP6B7dQ), maybe it is not up-to-date (IAM?). Is there a solution?

**Comment by hammoaj** [comment]
Latest 2.0.1 version support IAM apikeys.
