### ISSUE TITLE
Function sendDocumentOnPayload duplicated

### ISSUE THREAD

**Issue by kwakwaversal** [hammoaj/node-red-contrib-cloudantplus#5]
The function `sendDocumentOnPayload` function has been copied verbatim within the following functions:

`CloudantOutNode`
https://github.com/hammoaj/node-red-contrib-cloudantplus/blob/master/cloudantplus.js#L223

and

`CloudantInNode`
https://github.com/hammoaj/node-red-contrib-cloudantplus/blob/master/cloudantplus.js#L467

I was going to raise a PR but wasn't sure if this was a stylistic choice or not.

Feel free to close if this is by design.

**Comment by Stwissel** [comment]
fixed in 0.4
