### ISSUE TITLE
Can't upload sensor data

### ISSUE THREAD

**Issue by martin9115** [hammoaj/node-red-contrib-cloudantplus#7]
Hi i like your project (https://flows.nodered.org/node/node-red-contrib-cloudantplus), but when i try to connect NR and Cloudant via this tutorial, i have this error (photo):
https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-creating-an-ibm-cloudant-instance-on-ibm-cloud

Can you help me, please? 
![2020-09-25-121440_800x480_scrot](https://user-images.githubusercontent.com/50946705/94343571-a9587700-0021-11eb-8d7d-285c17062d25.png)

**Comment by martin9115** [comment]
I change the host and re-check the rest fields and now i have only this error:
![2020-10-26-155602_800x480_scrot](https://user-images.githubusercontent.com/50946705/97202477-59a1d280-17bc-11eb-82b9-9831c1281828.png)

**Comment by hammoaj** [comment]
New 0.4 release coming which will use the new Cloudant SDK. Should resolve
